apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- flux-system
- ../../apps/nginx
- ../../apps/api
- ../../infrastructure/monitoring
- ../../infrastructure/tracing
- ../../apps/aiops
